//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolrExpress {
    using System;
    using System.Reflection;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_pt_BR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_pt_BR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolrExpress.Resource-pt-BR", typeof(Resource_pt_BR).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parâmetro &quot;{0}&quot; não pode ser adicionado por já existir uma outra instância com o mesmo tipo.
        /// </summary>
        public static string AllowMultipleInstancesException {
            get {
                return ResourceManager.GetString("AllowMultipleInstancesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrado uma instância que implemente ICustomSolrConnectionAuthenticationSettings.
        /// </summary>
        public static string CustomSolrConnectionAuthenticationNotFoundException {
            get {
                return ResourceManager.GetString("CustomSolrConnectionAuthenticationNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expressão deve referenciar uma propriedade.
        /// </summary>
        public static string ExpressionMustBePropertyException {
            get {
                return ResourceManager.GetString("ExpressionMustBePropertyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo deve ser &quot;indexed=true&quot; para ser usado nessa função.
        /// </summary>
        public static string FieldMustBeIndexedTrueToBeUsedInThisFunctionException {
            get {
                return ResourceManager.GetString("FieldMustBeIndexedTrueToBeUsedInThisFunctionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo deve ser numérico ou de data para ser usado em facet range.
        /// </summary>
        public static string FieldMustBeNumericOrDateTimeToBeUsedInFacetRangeException {
            get {
                return ResourceManager.GetString("FieldMustBeNumericOrDateTimeToBeUsedInFacetRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo deve ser &quot;stored=true&quot; para ser usado nessa função.
        /// </summary>
        public static string FieldMustBeStoredTrueToBeUsedInThisFunctionException {
            get {
                return ResourceManager.GetString("FieldMustBeStoredTrueToBeUsedInThisFunctionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude deve estar entre -90.0 e 90.0.
        /// </summary>
        public static string InvalidLatitudeException {
            get {
                return ResourceManager.GetString("InvalidLatitudeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude deve estar entre -180.0 e 180.0.
        /// </summary>
        public static string InvalidLongitudeException {
            get {
                return ResourceManager.GetString("InvalidLongitudeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parâmetro &quot;{0}&quot; é inválido
        ///Mensagem de erro: {1}.
        /// </summary>
        public static string SearchParameterIsInvalidException {
            get {
                return ResourceManager.GetString("SearchParameterIsInvalidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown to resolve the expression.
        /// </summary>
        public static string UnknownToResolveExpressionException {
            get {
                return ResourceManager.GetString("UnknownToResolveExpressionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordenação do tipo descendente é um aspecto não suportado no Solr 4.
        /// </summary>
        public static string UnsupportedFeatureException {
            get {
                return ResourceManager.GetString("UnsupportedFeatureException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O parâmetro &quot;{0}&quot; possui uma versão específica.
        /// </summary>
        public static string UseSpecificParameterRatherThanAnyException {
            get {
                return ResourceManager.GetString("UseSpecificParameterRatherThanAnyException", resourceCulture);
            }
        }
    }
}
