//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolrExpress.Core {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_pt_BR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resource_pt_BR() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
#if NETCORE
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolrExpress.Core.Resource-pt-BR", typeof(Resource_pt_BR).GetTypeInfo().Assembly);
#else  
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolrExpress.Core.Resource-pt-BR", typeof(Resource_pt_BR).Assembly);
#endif
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Parâmetro &quot;{0}&quot; não pode ser adicionado por já existir uma outra instância com o mesmo tipo.
        /// </summary>
        public static string AllowMultipleInstanceOfParameterTypeException {
            get {
                return ResourceManager.GetString("AllowMultipleInstanceOfParameterTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expressão deve referenciar uma propriedade.
        /// </summary>
        public static string ExpressionMustBePropertyException {
            get {
                return ResourceManager.GetString("ExpressionMustBePropertyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Um campo deve ser &quot;indexed=true&quot; para ser usado em facet.
        /// </summary>
        public static string FieldMustBeIndexedTrueToBeUsedInAFacet {
            get {
                return ResourceManager.GetString("FieldMustBeIndexedTrueToBeUsedInAFacet", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Um campo deve ser &quot;indexed=true&quot; para ser usado em query.
        /// </summary>
        public static string FieldMustBeIndexedTrueToBeUsedInAQuery {
            get {
                return ResourceManager.GetString("FieldMustBeIndexedTrueToBeUsedInAQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Um campo deve ser &quot;indexed=true&quot; para ser usado em sort.
        /// </summary>
        public static string FieldMustBeIndexedTrueToBeUsedInASortException {
            get {
                return ResourceManager.GetString("FieldMustBeIndexedTrueToBeUsedInASortException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Um campo deve ser numérico ou de data para ser usado em facet range.
        /// </summary>
        public static string FieldMustBeNumericOrDateTimeToBeUsedInFacetRange {
            get {
                return ResourceManager.GetString("FieldMustBeNumericOrDateTimeToBeUsedInFacetRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Um campo deve ser &quot;stored=true&quot; para ser usado em fields.
        /// </summary>
        public static string FieldMustBeStoredTrueToBeUsedInFields {
            get {
                return ResourceManager.GetString("FieldMustBeStoredTrueToBeUsedInFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A latitude deve estar entre -90.0 e 90.0.
        /// </summary>
        public static string InvalidLatitudeException {
            get {
                return ResourceManager.GetString("InvalidLatitudeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A longitude deve estar entre -18.0 e 180.0.
        /// </summary>
        public static string InvalidLongitudeException {
            get {
                return ResourceManager.GetString("InvalidLongitudeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Parâmetro &quot;{0}&quot;, mensagem de validação: &quot;{1}&quot;.
        /// </summary>
        public static string InvalidParameterTypeException {
            get {
                return ResourceManager.GetString("InvalidParameterTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to O parâmetro &quot;{0}&quot; não foi encontrado no json de origem.
        /// </summary>
        public static string UnexpectedJsonException {
            get {
                return ResourceManager.GetString("UnexpectedJsonException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Não existe resolução para a requisição efetuada ao Solr
        ///Informações da solicitação:
        ///{0}
        ///
        ///Mensagem do servidor:
        ///{1}.
        /// </summary>
        public static string UnexpectedSolrRequestException {
            get {
                return ResourceManager.GetString("UnexpectedSolrRequestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Não foi possível efetuar a conversão por causa que o builder &quot;{0}&quot; não implementa IConvertJsonObject ou IConvertJsonPlainText.
        /// </summary>
        public static string UnknownResolveResultBuilderException {
            get {
                return ResourceManager.GetString("UnknownResolveResultBuilderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Não existe resolução para a expressão.
        /// </summary>
        public static string UnknownToResolveExpressionException {
            get {
                return ResourceManager.GetString("UnknownToResolveExpressionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ordenação do tipo descendente é um aspecto não suportado no Solr 4.
        /// </summary>
        public static string UnsupportedSortTypeException {
            get {
                return ResourceManager.GetString("UnsupportedSortTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to O parâmetro &quot;{0}&quot; possui uma versão específica.
        /// </summary>
        public static string UseSpecificParameterRatherThanAnyException {
            get {
                return ResourceManager.GetString("UseSpecificParameterRatherThanAnyException", resourceCulture);
            }
        }
    }
}
