//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolrExpress.Core {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resource() {
        }

        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
#if NETCORE
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolrExpress.Core.Resource", typeof(Resource).GetTypeInfo().Assembly);
#else  
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolrExpress.Core.Resource", typeof(Resource).Assembly);
#endif
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Parameter &quot;{0}&quot; is not allowed because another instance of the same type was added.
        /// </summary>
        public static string AllowMultipleInstanceOfParameterTypeException {
            get {
                return ResourceManager.GetString("AllowMultipleInstanceOfParameterTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expression must be a property reference.
        /// </summary>
        public static string ExpressionMustBePropertyException {
            get {
                return ResourceManager.GetString("ExpressionMustBePropertyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A field must be &quot;indexed=true&quot; to be used in a facet.
        /// </summary>
        public static string FieldMustBeIndexedTrueToBeUsedInAFacetException {
            get {
                return ResourceManager.GetString("FieldMustBeIndexedTrueToBeUsedInAFacetException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A field must be &quot;indexed=true&quot; to be used in a query.
        /// </summary>
        public static string FieldMustBeIndexedTrueToBeUsedInAQueryException {
            get {
                return ResourceManager.GetString("FieldMustBeIndexedTrueToBeUsedInAQueryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A field must be &quot;indexed=true&quot; to be used in a sort.
        /// </summary>
        public static string FieldMustBeIndexedTrueToBeUsedInASortException {
            get {
                return ResourceManager.GetString("FieldMustBeIndexedTrueToBeUsedInASortException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A field must be numeric or DateTime to be used in a facet range.
        /// </summary>
        public static string FieldMustBeNumericOrDateTimeToBeUsedInFacetRangeException {
            get {
                return ResourceManager.GetString("FieldMustBeNumericOrDateTimeToBeUsedInFacetRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A field must be &quot;stored=true&quot; to be used in field list.
        /// </summary>
        public static string FieldMustBeStoredTrueToBeUsedInFieldsException {
            get {
                return ResourceManager.GetString("FieldMustBeStoredTrueToBeUsedInFieldsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Latitude most be inside range from -90.0 to 90.0.
        /// </summary>
        public static string InvalidLatitudeException {
            get {
                return ResourceManager.GetString("InvalidLatitudeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Longitude most be inside range from -180.0 to 180.0.
        /// </summary>
        public static string InvalidLongitudeException {
            get {
                return ResourceManager.GetString("InvalidLongitudeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Parameter &quot;{0}&quot; validation message: &quot;{1}&quot;.
        /// </summary>
        public static string InvalidParameterTypeException {
            get {
                return ResourceManager.GetString("InvalidParameterTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Parameter &quot;{0}&quot; was not found in the source json.
        /// </summary>
        public static string UnexpectedJsonException {
            get {
                return ResourceManager.GetString("UnexpectedJsonException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unknown to resolve solr query request
        ///Requested instruction:
        ///{0}
        ///
        ///Server message:
        ///{1}.
        /// </summary>
        public static string UnexpectedSolrRequestException {
            get {
                return ResourceManager.GetString("UnexpectedSolrRequestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unknown resolve of the result builder type &quot;{0}&quot; because this type doesn&apos;t implement IConvertJsonObject or IConvertJsonPlainText.
        /// </summary>
        public static string UnknownResolveResultBuilderException {
            get {
                return ResourceManager.GetString("UnknownResolveResultBuilderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unknown to resolve the expression.
        /// </summary>
        public static string UnknownToResolveExpressionException {
            get {
                return ResourceManager.GetString("UnknownToResolveExpressionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Security system is an unsupported feature in Solr 4.
        /// </summary>
        public static string UnsupportedSecuritySystemException {
            get {
                return ResourceManager.GetString("UnsupportedSecuritySystemException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Descending sort type is an unsupported feature in Solr 4.
        /// </summary>
        public static string UnsupportedSortTypeException {
            get {
                return ResourceManager.GetString("UnsupportedSortTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Parameter &quot;{0}&quot; have a specific version.
        /// </summary>
        public static string UseSpecificParameterRatherThanAnyException {
            get {
                return ResourceManager.GetString("UseSpecificParameterRatherThanAnyException", resourceCulture);
            }
        }
    }
}
